# Generated by Django 3.0.7 on 2021-02-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='useComment',
            new_name='userComment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='usePost',
            new_name='userPost',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(max_length=20),
        ),
    ]
